[package]
name = "rust-xpx-chain-sdk"
version = "0.1.0"
readme = "README.md"
license = "Apache-2.0"
authors = ["Eleazar Garrido <eleazar.garrido@proximax.io>"]
homepage = "https://www.proximax.io"
repository = "https://github.com/proximax-storage/rust-xpx-chain-sdk"
documentation = "https://github.com/proximax-storage/rust-xpx-chain-sdk/wiki"
keywords = ["blockchain", "sdk"]
categories = ["sdk"]
exclude = [ ".gitignore" ]
edition = "2018"

[lib]
name = "xpx_chain_sdk"
crate-type = ["lib"]

[dependencies]
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
serde_yaml = "0.7"
erased-serde = "0.3"

rust-xpx-crypto = { path = "../rust-xpx-crypto" }

url = "2.1"
hyper = "0.13"
tokio = { version = "0.2", features = ["macros"] }
base64 = "0.7.0"
futures = "0.3.4"
base32 = "0.4.0"
ripemd160 = "0.8.0"
hex = "^0.3"
regex = "1"
byteorder = "1"
async-trait = "0.1.24"
bytes = { version = "0.5", features = ["serde"] }

more-asserts = "0.2.1"

[dependencies.rand]
version = "0.6"
default-features = false

[dependencies.failure]
version = "0.1"

[dependencies.sha3]
version = "^0.8"
default-features = false

[dev-dependencies]
#tokio = "*"
